services:
  app:
    #if you want to set container name,enter the container name here
    #container_name: YOUR_CONTAINER_NAME
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3100:3000"
    # start development server
    command: bash -c "npm run dev"