[package]
name = "search-word"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
error_handle = []

[dependencies]
"word_distance" = { path = "word_distance" }
wasm-bindgen = "0.2.95"
console_error_panic_hook = "0.1.7"
csv = "1.3.0"
